Library/urls.py
__author__ = 'DELL'

from django.urls import path
from .import views

app_name='Library'

urlpatterns = [

    path('Technology',views.tech,name="tech"),
    path('Chemical',views.chem,name="chem"),
    path('Biotechnology',views.bio,name="bio"),
    path('Electronics',views.elec,name="elec"),
    path('Mechanical',views.mech,name="mech"),

]

Students/urls.py
__author__ = 'DELL'
from django.urls import path
from .import  views

app_name="Students"

urlpatterns=[
    path('mainprofile',views.mainprofile,name="mainprofile"),
    path('editprofile',views.editprofile,name="editprofile"),

]

WEBSITE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Library/',include('Library.urls')),
    #path('Accounts/',include('Accounts.urls')),
    path('',views.homepage,name="homepage"),
    path('login/',views.loginn,name="login"),
    path('email/',views.email,name="email"),
    path('Student/',include('Students.urls')),
    path('Teachers/',include('Teachers.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

Students/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class registertable(models.Model):
    uname=models.IntegerField()
    name=models.CharField(max_length=300)
    department=models.CharField(max_length=300)
    year=models.IntegerField()
    email=models.EmailField(max_length=120)
    password=models.CharField(max_length=300)
    reg_type=models.CharField(max_length=300)
    

    
    def __str__(self):
        return self.name
# Create your models here.

Students/views.py
from django.shortcuts import render

# Create your views here.

def mainprofile(request):
    if request.method=='POST':
        pass

    return render(request,'Students/main_profile.html')

def editprofile(request):

    return render(request,'Students/edit_profile.html')

Students/templates/Students/base_layout.html
{%  load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Student</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<style type="text/css">
		header{
			background: white;
		}
	</style>
    <script type="text/javascript">
		document.getElementById("stu_prof").classList.add("active");
	</script>
    <style type="text/css">
		.green{
			border-left:5px solid #71E4B9;
			border-right:5px solid #71E4B9;
		}

		.details{
			margin:20px 30px;
			font-size: 20px;
			color: #5894C3;
		}
		.desc{
			color:#9EA6BB;
			padding-left:10px;
		}
	</style>
</head>


<body>
    <header>
		<div class="container">
			<div id="header">
				<img id="logo" src="{% static 'logo.png' %}">
				<img id="logo1" src="{% static 'logo1.png' %}" style="float:right;">
			</div>
			<div id="head_section">
				<div id="head_display">
					<img src="{% static 'avatar.png' %}" style="height:150px; width:150px;">
				</div>
				<div id="head_name">
					<h1>NAME:{{userdata.name}}</h1>
					<h4>EMAIL:{{userdata.email}}</h4>
					<!--<h4 id="head_pre">Department:{{dept}}  </h4>
					<h4 id="head_pre">Year:{{year}}  </h4>-->

				</div>
			</div>
		</div>
	</header>

	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  			<ul class="nav nav-tabs nav-justified" style="padding-left:270px;">
	    			<li class="active"><a href="{% url 'Students:mainprofile' %}">PROFILE</a></li>
	    			<!--<li><a href="classroom.html">CLASSROOM</a></li>-->
	    			<li  ><a href="{% url 'Library:tech' %}">LIBRARY</a></li>
	    			<li><a href="contacts.html">CONTACTS</a></li>
	  			</ul>
			</div>
		</nav>

            {% block content %}
            {% endblock %}
        	</div>
		</div>
<footer id="foot">
		<table id="foot_tbl">
			<tr>
				<td>
					<ul class="foot_ul">
						<li><a href='#'>About Us</a></li>
						<br>
						<li><a href='#'>Contact</a></li>
						<br>
						<li><a href='#'>Terms and Conditions</a></li>
					</ul>
				</td>
				<td style="width:250px;">
					<ul class="foot_ul" style="padding-left:10px">
						<li><i class="fab fa-facebook-f"></i>  <a href='#'>Facebook</a></li>
						<br>
						<li><i class="fab fa-instagram"></i>  <a href='#'>Instagram</a></li>
						<br>
						<li><i class="fab fa-twitter"></i>  <a href='#'>Twitter</a></li>
					</ul>
				</td>
				<td>
					<br>
					<form>
					Subscribe to our newsletter:
					<br>
					<br>
					<input type="text" name="email_news" placeholder="Email Address">
					<input type="submit" value="Subscribe">
					</form>
					<br>
				</td>
				<td>
					<br>
					<br>
					<pre id="foot_pre">Dwarkadas Jivanlal College Of Enginerring,
U-15, Bhaktivedanta Swami Marg,
Navpada, Suvarna Nagar,
Vile Parle West,
Mumbai,
Maharashtra 400056
					</pre>
					<br>
				</td>
			</tr>
		</table>
	</footer>
</body>
</html>

Students/templates/Students/edit_profile.html
<!DOCTYPE html>
<html>
<head>
	<title>Edit Profile</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="main.css">
	<style type="text/css">
		body{
			padding-top: 70px;
		}
		.details{
			margin:20px 30px;
			font-size: 20px;
			color: #5894C3;
		}
		.tab{
			border:1px solid black;
			margin:20px 40px;
			padding-bottom: 20px;
    		background: rgba(0, 0, 0, 0.1);
		}
		label{
			margin: 20px 6px;
			padding-left: 50px;
    		width: 250px;
		}

		i,.tab button{
			margin-left:25px;
		}
		input:not(#savebtn){
			border-radius: 5px;
			height: 40px;
			padding: 5px;
			width:25%;
			margin-right: 20px;
		}
		#skill, #projects {
			text-align: center;
			list-style-type: none;
		}
	</style>
	<script type="text/javascript">
		var skills = [];
		function AddSkill() {
			var skill="";
			skills.push(document.querySelector("#skills").value);
			for (var i = 0; i < skills.length; i++) {
			skill+="<li>"+skills[i]+"</li>\n";
			}
			document.querySelector("#skill").innerHTML = skill ;
			document.querySelector("#skills").value="";
			}
		var projects = []
		function AddProj() {
			var proj="";
			projects.push(document.querySelector("#proj").value);
			for (var i = 0; i < projects.length; i++) {
			proj+="<li>"+projects[i]+"</li>\n";
			}
			document.querySelector("#projects").innerHTML = proj ;
			document.querySelector("#proj").value="";
			}
		function AddAchievement(){
			document.querySelector("#achieve").innerHTML = "<i class='fas fa-check'></i><b>&nbsp;Added</b>";
			document.querySelector("#certi").value = "";
			document.querySelector("#rank").value = "";
			document.querySelector("#Institute").value = "";
			document.querySelector("#describe").value = "";
		}
		function AddExtra(){
			document.querySelector("#extra").innerHTML = "<i class='fas fa-check'></i><b>&nbsp;Added</b>";
			document.querySelector("#course").value = "";
			document.querySelector("#inst").value = "";
			document.querySelector("#from").value = "";
			document.querySelector("#to").value = "";
		}
		function remove(){
			document.querySelector("#achieve").innerHTML = "";
			document.querySelector("#extra").innerHTML = "";
		}

	</script>
</head>
<body>
	<div class="container">
		<div class= "box-main">
			<form id="regForm" action="/action_page.php">
			  <h1 style="text-align: center;">EDIT PROFILE</h1>
			  <!-- One "tab" for each step in the form: -->
			  <div class="tab">
			    <h3 class="details">PERSONAL DETAILS</h3>
			    <label>Name:</label>
			    <input placeholder="Enter your First name"  name="fname">
			    <input placeholder=" Enter your Last name"  name="lname">
			    <br>
			    <label>SAP ID:</label>
			    <input placeholder="Enter your SAP ID"  name="sap">
			    <br>
			    <label>Contact Info:</label>
			    <input placeholder="Enter your E-mail"  name="email">
			    <input placeholder="Enter your Phone"  name="phone">
			    <br>
			    <label>Birthday:</label>
			    <input type="date"  name="dob">
			    <br>
			  </div>
			  <div class="tab">
			    <h3 class="details">ACADEMIC DETAILS</h3>
			    <label>10th:</label>
			    <input placeholder="Enter your School Name"  name="school">
			    <br>
			    <label>12th/Diploma:</label>
			    <input placeholder="Enter the Institute Name"  name="college">
			  </div>
			  <div class="tab">
			    <h3 class="details">EXTRACURRICULAR</h3>
			    <i>Enter courses/workshops you have attended here!</i><br/><br/>
			   <label> Course name:</label>
			    <input placeholder="Enter the Course" id="course" name="course" onfocus="remove()">
			    <br>
			    <label>Institute name:</label>
			    <input placeholder="Enter your Institute Name" id="inst" name="inst">
			    <br>
			    <label>From: </label><input type="date" id="from" name="">
			    <br>
			    <label>To:</label> <input type="date" id="to" name="">
			    <br>
			    <br>
			    <button type="button" id="addcourse" class="btn btn-primary" onclick="AddExtra()">ADD</button>
			    <span style="margin:30px;" id="extra"></span>
			  </div>
			  <div class="tab">
			    <h3 class="details">ACHIEVEMENTS</h3>
			    <i>"Showoff your achievements"</i><br/><br/>
			    <label>Name of Certificate:</label>
			    <input placeholder="Name" id="certi" name="certi" required onfocus="remove()">
			    <br>
			    <label>Rank:</label>
			    <input placeholder="Rank" id="rank" name="rank">
			    <br>
			    <label>Institute name:</label>
			    <input placeholder="Institute Name" id="Institute" name="Institute" required >
			    <input placeholder="Description" id="describe" name ="describe">
			    <br>
			    <br>
			    <button type="button" id="addcerti" class="btn btn-primary" onclick="AddAchievement()">ADD</button>
			    <span style="margin:30px;" id="achieve"></span>
			  </div>
			  <div class="tab">
			  <h3 class="details">PERSONAL DEVELOPMENT</h3>
		      <i>"Potray your skills and back them by displaying you projects!"</i><br/><br/>
		      <table>
		      <tr>
		      <td>
		      <label>SKILLS:</label>
		      <input placeholder="Skills" id="skills" name="skills" >
		  	  </td>
		  	  <td>
		  	  <label>PROJECTS:</label>
		      <input placeholder="Project link" id="proj" name="proj">
		  	  </td>
		  	  </tr>
		  	  <tr>
		  	  	<td><button type="button" id="addskill" class="btn btn-primary" style="float: right" onclick="AddSkill()">ADD</button><br/><br/></td>
		      	<td><button type="button" id="addproj" class="btn btn-primary" style="float: right" onclick="AddProj()">ADD</button><br/><br/></td>
		      </tr>
		      <tr>
		      	<td>
		      		<ul id="skill">
		      		</ul>
		      	</td>
		      	<td>
		      		<ul id="projects">
		      		</ul>
		      	</td>
		      </tr>
		      <table>
			  </div>
			  <div style="overflow:auto;">
			      <input type="reset" class="btn btn-success" style="margin-left: 920px; margin-top: 50px;" value="Save" id="savebtn"></input>
			  </div>
			</form>
		</div>
	</div>
</body>
</html>

Students/templates/Students/main_profile.html
{% extends 'Students/base_layout.html' %}
{%  load static from staticfiles %}

{% block content %}


	<div class="container">
		<a style="text-decoration: none;" href="{% url 'Students:editprofile' %}"><button type="button" class="btn btn-danger" style="float: right;"><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="padding-right:5px;"></span> Edit Profile</button></a>
		<br>
		<br>
		<br>
		<div class= "box-main">
			<div class="box-der green">
				<span style="padding-left: 10px; color:#9EA6BB;"><em>About me</em></span>
			</div>
			<h4 class="details">Academic Details</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1+
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Achievements</h4>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Training</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Skills</h4>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Projects</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="Profile.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
		</div>
		<div style="clear: both;"></div>
	</div>
{% endblock %}