Library/urls.py
__author__ = 'DELL'

from django.urls import path
from .import views

app_name='Library'

urlpatterns = [

    path('Technology',views.tech,name="tech"),
    path('Chemical',views.chem,name="chem"),
    path('Biotechnology',views.bio,name="bio"),
    path('Electronics',views.elec,name="elec"),
    path('Mechanical',views.mech,name="mech"),

]

WEBSITE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Library/',include('Library.urls')),
    #path('Accounts/',include('Accounts.urls')),
    path('',views.homepage,name="homepage"),
    path('login/',views.loginn,name="login"),
    path('email/',views.email,name="email"),
    path('Student/',include('Students.urls')),
    path('Teachers/',include('Teachers.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

Library/models.py
from django.db import models

# Create your models here.

class Tech_Model(models.Model):
    icon=models.ImageField()
    book_name= models.CharField(max_length=100)
    book_author= models.CharField(max_length=50)
    issued= models.BooleanField()
    copies= models.IntegerField()


    def __str__(self):
        return self.book_name


class Chem_Model(models.Model):
    icon=models.ImageField()
    book_name= models.CharField(max_length=100)
    book_author= models.CharField(max_length=50)
    issued= models.BooleanField()
    copies= models.IntegerField()


    def __str__(self):
        return self.book_name

class Elec_Model(models.Model):
    icon=models.ImageField()
    book_name= models.CharField(max_length=100)
    book_author= models.CharField(max_length=50)
    issued= models.BooleanField()
    copies= models.IntegerField()


    def __str__(self):
        return self.book_name

class Bio_Model(models.Model):
    icon=models.ImageField()
    book_name= models.CharField(max_length=100)
    book_author= models.CharField(max_length=50)
    issued= models.BooleanField()
    copies= models.IntegerField()


    def __str__(self):
        return self.book_name

class Mech_Model(models.Model):
    icon=models.ImageField()
    book_name= models.CharField(max_length=100)
    book_author= models.CharField(max_length=50)
    issued= models.BooleanField()
    copies= models.IntegerField()


    def __str__(self):
        return self.book_name

Library/views.py
from django.shortcuts import render
from .models import Tech_Model,Chem_Model,Elec_Model,Mech_Model,Bio_Model
# Create your views here.

def tech(request):

    books = Tech_Model.objects.all()
    print(books)



    if request.method=='POST':

        print("POST request")
        return render(request, 'Library/library-tech.html',{'books':books})


    print("GET request")

    return render(request,'Library/library-tech.html',{'books':books})


def bio(request):

    books = Bio_Model.objects.all()
    if request.method=='POST':
        print("POST request")
        return render(request, 'Library/library-bio.html')


        #print("GET request")

    return render(request,'Library/library-bio.html',{'books':books})

def elec(request):

    books = Elec_Model.objects.all()
    if request.method=='POST':
        print("POST request")
        return render(request, 'Library/library-elec.html')


        #print("GET request")

    return render(request,'Library/library-elec.html',{'books':books})

def mech(request):

    books = Mech_Model.objects.all()
    if request.method=='POST':
        print("POST request")
        return render(request, 'Library/library-mech.html')


        #print("GET request")

    return render(request,'Library/library-mech.html',{'books':books})

def chem(request):

    books = Chem_Model.objects.all()
    issued = Chem_Model.objects.filter('issued')
    copies = Chem_Model.objects.filter('copies')



    if request.method=='POST' and copies != 0:
        c = Chem_Model()
        c.copies = copies-1
        c.save()
        print("POST request")
        return render(request, 'Library/library-chem.html')


        #print("GET request")

    return render(request,'Library/library-chem.html',{'books':books})

Library/templates/Library/library-bio.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class= "box-main">
			<nav class="navbar navbar-default box-nav">
			  	<div class="container">
			    	<ul class="nav navbar-nav">
				      <li class="active"><a href="{% url 'Library:tech' %}">TECHNOLOGY</a></li>
				      <li><a href="{% url 'Library:chem' %}">CHEMICAL</a></li>
				      <li><a href="{% url 'Library:bio' %}">BIOMEDICAL</a></li>
				      <li><a href="{% url 'Library:mech' %}">MECHANICAL</a></li>
				      <li><a href="{% url 'Library:elec' %}">ELECTRONICS</a></li>
			    	</ul>
			 	</div>
			</nav>
			<div class="inner-addon">
    			<i class="fas fa-search left-addon"></i>
    			<span><a href="#"><i class="fas fa-arrow-right right-addon"></i></a></span>
    			<input type="text" name="search_lib" placeholder=" Search book by name..." style="margin-left: 30px; border-radius: 2px; padding:5px 30px;">
			</div>
			<div class="row">
  				<div class="col-xs-6 col-sm-3">
                    {% for book in books %}
  					<div class="col">
			  			<img src="{{ book.icon.url }}" width="60" height="80">
			  			<h4><strong>{{ book.book_name }}</strong></h4>
			  			<h4 style="color:#9EA6BB;">{{ book.book_author }}</h4>
                        <h4 style="color:#9EA6BB;">Copies :{{ book.copies }}</h4>

			  			<button type="button" class="btn btn-primary btn-lg">Issue</button>
  					</div>
                    {% endfor %}
  				</div>

			</div>
{% endblock %}

Library/templates/Library/library-chem.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class= "box-main">
			<nav class="navbar navbar-default box-nav">
			  	<div class="container">
			    	<ul class="nav navbar-nav">
				      <li class="active"><a href="{% url 'Library:tech' %}">TECHNOLOGY</a></li>
				      <li><a href="{% url 'Library:chem' %}">CHEMICAL</a></li>
				      <li><a href="{% url 'Library:bio' %}">BIOMEDICAL</a></li>
				      <li><a href="{% url 'Library:mech' %}">MECHANICAL</a></li>
				      <li><a href="{% url 'Library:elec' %}">ELECTRONICS</a></li>
			    	</ul>
			 	</div>
			</nav>
			<div class="inner-addon">
    			<i class="fas fa-search left-addon"></i>
    			<span><a href="#"><i class="fas fa-arrow-right right-addon"></i></a></span>
    			<input type="text" name="search_lib" placeholder=" Search book by name..." style="margin-left: 30px; border-radius: 2px; padding:5px 30px;">
			</div>
			<div class="row">
  				<div class="col-xs-6 col-sm-3">
                    {% for book in books %}
  					<div class="col">
			  			<img src="{{ book.icon.url }}" width="60" height="80">
			  			<h4><strong>{{ book.book_name }}</strong></h4>
			  			<h4 style="color:#9EA6BB;">{{ book.book_author }}</h4>
                        <h4 style="color:#9EA6BB;">Copies :{{ book.copies }}</h4>

			  			<button type="button" class="btn btn-primary btn-lg">Issue</button>
  					</div>
                    {% endfor %}
  				</div>

			</div>
{% endblock %}

Library/templates/Library/library-elec.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class= "box-main">
			<nav class="navbar navbar-default box-nav">
			  	<div class="container">
			    	<ul class="nav navbar-nav">
				      <li class="active"><a href="{% url 'Library:tech' %}">TECHNOLOGY</a></li>
				      <li><a href="{% url 'Library:chem' %}">CHEMICAL</a></li>
				      <li><a href="{% url 'Library:bio' %}">BIOMEDICAL</a></li>
				      <li><a href="{% url 'Library:mech' %}">MECHANICAL</a></li>
				      <li><a href="{% url 'Library:elec' %}">ELECTRONICS</a></li>
			    	</ul>
			 	</div>
			</nav>
			<div class="inner-addon">
    			<i class="fas fa-search left-addon"></i>
    			<span><a href="#"><i class="fas fa-arrow-right right-addon"></i></a></span>
    			<input type="text" name="search_lib" placeholder=" Search book by name..." style="margin-left: 30px; border-radius: 2px; padding:5px 30px;">
			</div>
			<div class="row">
  				<div class="col-xs-6 col-sm-3">
                    {% for book in books %}
  					<div class="col">
			  			<img src="{{ book.icon.url }}" width="60" height="80">
			  			<h4><strong>{{ book.book_name }}</strong></h4>
			  			<h4 style="color:#9EA6BB;">{{ book.book_author }}</h4>
                        <h4 style="color:#9EA6BB;">Copies :{{ book.copies }}</h4>

			  			<button type="button" class="btn btn-primary btn-lg">Issue</button>
  					</div>
                    {% endfor %}
  				</div>

			</div>
{% endblock %}

Library/templates/Library/library-mech.html
{% extends 'base_layout.html' %}
        {% block content %}
            <div class= "box-main">
			<nav class="navbar navbar-default box-nav">
			  	<div class="container">
			    	<ul class="nav navbar-nav">
				      <li class="active"><a href="{% url 'Library:tech' %}">TECHNOLOGY</a></li>
				      <li><a href="{% url 'Library:chem' %}">CHEMICAL</a></li>
				      <li><a href="{% url 'Library:bio' %}">BIOMEDICAL</a></li>
				      <li><a href="{% url 'Library:mech' %}">MECHANICAL</a></li>
				      <li><a href="{% url 'Library:elec' %}">ELECTRONICS</a></li>
			    	</ul>
			 	</div>
			</nav>
			<div class="inner-addon">
    			<i class="fas fa-search left-addon"></i>
    			<span><a href="#"><i class="fas fa-arrow-right right-addon"></i></a></span>
    			<input type="text" name="search_lib" placeholder=" Search book by name..." style="margin-left: 30px; border-radius: 2px; padding:5px 30px;">
			</div>
			<div class="row">
  				<div class="col-xs-6 col-sm-3">
                    {% for book in books %}
  					<div class="col">
			  			<img src="{{ book.icon.url }}" width="60" height="80">
			  			<h4><strong>{{ book.book_name }}</strong></h4>
			  			<h4 style="color:#9EA6BB;">{{ book.book_author }}</h4>
                        <h4 style="color:#9EA6BB;">Copies :{{ book.copies }}</h4>

			  			<button type="button" class="btn btn-primary btn-lg">Issue</button>
  					</div>
                    {% endfor %}
  				</div>
            </div>
        {% endblock %}

Library/templates/Library/library-tech.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class= "box-main">
			<nav class="navbar navbar-default box-nav">
			  	<div class="container">
			    	<ul class="nav navbar-nav">
				      <li class="active"><a href="{% url 'Library:tech' %}">TECHNOLOGY</a></li>
				      <li><a href="{% url 'Library:chem' %}">CHEMICAL</a></li>
				      <li><a href="{% url 'Library:bio' %}">BIOMEDICAL</a></li>
				      <li><a href="{% url 'Library:mech' %}">MECHANICAL</a></li>
				      <li><a href="{% url 'Library:elec' %}">ELECTRONICS</a></li>
			    	</ul>
			 	</div>
			</nav>
			<div class="inner-addon">
    			<i class="fas fa-search left-addon"></i>
    			<span><a href="#"><i class="fas fa-arrow-right right-addon"></i></a></span>
    			<input type="text" name="search_lib" placeholder=" Search book by name..." style="margin-left: 30px; border-radius: 2px; padding:5px 30px;">
			</div>
			<div class="row">
  				<div class="col-xs-6 col-sm-3">
                    {% for book in books %}
  					<div class="col">
			  			<img src="{{ book.icon.url }}" width="60" height="80">
			  			<h4><strong>{{ book.book_name }}</strong></h4>
			  			<h4 style="color:#9EA6BB;">{{ book.book_author }}</h4>
                        <h4 style="color:#9EA6BB;">Copies :{{ book.copies }}</h4>
                        <form method="POST">
                            {% csrf_token %}
			  			<button type="submit" class="btn btn-primary btn-lg">Issue</button>
                        </form>
  					</div>
                    {% endfor %}
  				</div>

			</div>
{% endblock %}