Library/urls.py
__author__ = 'DELL'

from django.urls import path
from .import views

app_name='Library'

urlpatterns = [

    path('Technology',views.tech,name="tech"),
    path('Chemical',views.chem,name="chem"),
    path('Biotechnology',views.bio,name="bio"),
    path('Electronics',views.elec,name="elec"),
    path('Mechanical',views.mech,name="mech"),

]

Students/urls.py
__author__ = 'DELL'
from django.urls import path
from .import  views

app_name="Students"

urlpatterns=[
    path('mainprofile',views.mainprofile,name="mainprofile"),
    path('editprofile',views.editprofile,name="editprofile"),

]

Teachers/urls.py
__author__ = 'DELL'
from django.urls import path
from django.conf.urls import url
from .import  views


app_name="Teachers"

urlpatterns=[
    path('mainprofile',views.mainprofile,name="mainprofile"),
    url(r'^editprofile',views.editprofile,name="editprofile"),

]

WEBSITE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Library/',include('Library.urls')),
    #path('Accounts/',include('Accounts.urls')),
    path('',views.homepage,name="homepage"),
    path('login/',views.loginn,name="login"),
    path('email/',views.email,name="email"),
    path('Student/',include('Students.urls')),
    path('Teachers/',include('Teachers.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

Teachers/models.py
from django.db import models
#from WEBSITE.models import registertable
class edit(models.Model):
	fname=models.CharField(max_length=300)
	lname=models.CharField(max_length=300)
	sapid=models.IntegerField()
	contact=models.IntegerField()
	email=models.EmailField(max_length=120)
	date=models.DateField()
	prof=models.TextField(max_length=600)
	qid = models.ManyToManyField('Qualification',on_delete=models.CASCADE)
	#sid = models.ForeignKey(specialization)
	about=models.TextField()
	def __str__(self):
		return u'%s %s %s %s %s %s %s' % (self.fname,self.lname,self.sapid,self.contact,self.email,self.date,self.prof,)
class qualification(models.Model):
	qidd = models.IntegerField(primary_key=True)
	degree = models.CharField(max_length=100)
	year = models.IntegerField()
	institute = models.CharField(max_length=200)
	def __str__(str):
		return u'%s %s %s %s' % (self.qid,self.degree,self.year,self.institute)







# Create your models here.

Teachers/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.db import models
from WEBSITE.models import User,registertable
from .models import edit 
@login_required
def mainprofile(request):
	print("hi")
	u=None
	editt=None
	c=None
	d=None
	if request.user.is_authenticated:
		print(request.user.username)
		c=str(request.user.username)

		d=int(c)
		if registertable.objects.filter(uname=c).exists():
			u=registertable.objects.get(uname=c)
		
		#edit.objects.all().delete()
		if edit.objects.filter(sapid=d).exists():
			editt=edit.objects.get(sapid=d)
		
		print(editt)
		
		#u=dict(u)
		
	return  render(request,'Teachers/mainpage.html',{'uu':u,'edittt':editt})
		    
    
   
def editprofile(request):
	u=None
	editt=None
	c=None
	d=None
	if request.method=="POST":
		 fname= request.POST.get('fname')
		 lname=request.POST.get('lname')
		 sapid= request.POST.get('sap')
		 contact=request.POST.get('phone')
		 email= request.POST.get('email')
		 profsum=request.POST.get('profsum')
		 dob=request.POST.get('dob')
		 if request.user.is_authenticated:
		 	print("entered")
		 	edit.objects.all().delete()
		 	data1={"firstname":fname,"lastname":lname,"sapidd":sapid,"contactinfo":contact,"emailid":email,"profsumm":profsum,"dob":dob}
		 	editt = edit(fname=fname,lname=lname,sapid=sapid,contact=contact,email=email,prof=profsum,date=dob)
		 	editt.save()
		 	c=str(request.user)
		 	d=int(c)
		 	u=registertable.objects.get(uname=c)
		 	editt = edit.objects.filter(sapid=d) 
		 	mainprofile(request)
		 	
			
	return render(request,'Teachers/editpage.html',{'uu':u,'edittt':editt})
        	
        	     
        	  	
        	
        	
    
        	
        	   
        	     	        	

        	
        	
        	
        	
    
         
         
        
        
        
        
    
       
        
        
        
			


		    
		    
			
			
		
		
		
		
		
		
		
		
		    
		
    
        
        

        
        
        

        

Teachers/templates/Teachers/base_teach.html
{%  load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>teacher</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{%static 'main.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<style type="text/css">
		header{
			background: white;
		}
	</style>
    <script type="text/javascript">
		document.getElementById("stu_prof").classList.add("active");
	</script>
    <style type="text/css">
		.green{
			border-left:5px solid #71E4B9;
			border-right:5px solid #71E4B9;
		}

		.details{
			margin:20px 30px;
			font-size: 20px;
			color: #5894C3;
		}
		.desc{
			color:#9EA6BB;
			padding-left:10px;
		}
	</style>
</head>


<body>
    <header>
		<div class="container">
			<div id="header">
				<img id="logo" src="{% static 'logo.png' %}">
				<img id="logo1" src="{% static 'logo1.png' %}" style="float:right;">
			</div>
			<div id="head_section">
				<div id="head_display">
					<img src="{% static 'avatar.png' %}" style="height:150px; width:150px;">
				</div>
				<div id="head_name">
					<h2>{{uu.name}}</h2>
					<h4 id="head_pre">{{uu.email}}</h4>
					<!--<h4 id="head_pre">Department:{{dept}}</h4>
					<h4 id="head_pre">Year:{{year}}</h4>-->


				</div>
			</div>
		</div>
	</header>

	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  			<ul class="nav nav-tabs nav-justified" style="padding-left:270px;">
	    			<li class="active"><a href="{% url 'Students:mainprofile' %}">PROFILE</a></li>
	    			<li  ><a href="{% url 'Library:tech' %}">LIBRARY</a></li>
	    			<li><a href="contacts.html">CONTACTS</a></li>
	  			</ul>
			</div>
		</nav>

            {% block content %}
            {% endblock %}
        	</div>
		</div>
<footer id="foot">
		<table id="foot_tbl">
			<tr>
				<td>
					<ul class="foot_ul">
						<li><a href='#'>About Us</a></li>
						<br>
						<li><a href='#'>Contact</a></li>
						<br>
						<li><a href='#'>Terms and Conditions</a></li>
					</ul>
				</td>
				<td style="width:250px;">
					<ul class="foot_ul" style="padding-left:10px">
						<li><i class="fab fa-facebook-f"></i>  <a href='#'>Facebook</a></li>
						<br>
						<li><i class="fab fa-instagram"></i>  <a href='#'>Instagram</a></li>
						<br>
						<li><i class="fab fa-twitter"></i>  <a href='#'>Twitter</a></li>
					</ul>
				</td>
				<td>
					<br>
					<form>
					Subscribe to our newsletter:
					<br>
					<br>
					<input type="text" name="email_news" placeholder="Email Address">
					<input type="submit" value="Subscribe">
					</form>
					<br>
				</td>
				<td>
					<br>
					<br>
					<pre id="foot_pre">Dwarkadas Jivanlal College Of Enginerring,
U-15, Bhaktivedanta Swami Marg,
Navpada, Suvarna Nagar,
Vile Parle West,
Mumbai,
Maharashtra 400056
					</pre>
					<br>
				</td>
			</tr>
		</table>
	</footer>
</body>
</html>

Teachers/templates/Teachers/editpage.html
{%  load static from staticfiles %}
<html>
<head>
	<title>Edit Profile</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{%static 'main.css' %}">
	<style type="text/css">
		body{
			padding-top: 70px;
		}
		.details{
			margin:20px 30px;
			font-size: 20px;
			color: #5894C3;
		}
		.tab{
			border:1px solid black;
			margin:20px 40px;
			padding-bottom: 20px;
    		background: rgba(0, 0, 0, 0.1);
		}
		label{
			margin: 20px 6px;
			padding-left: 50px;
    		width: 250px;
		}

		i,.tab button{
			margin-left:25px;
		}
		input:not(#savebtn){
			border-radius: 5px;
			height: 40px;
			margin-right: 20px;
			padding: 5px;
			width:25%;
		}

		#describe{
			padding-left: 100px;
		}

		#skill, #projects {
			text-align: center;
			list-style-type: none;
		}
	</style>
	<script type="text/javascript">
		var skills = [];
		function AddSkill() {
			var skill="";
			skills.push(document.querySelector("#skills").value);
			for (var i = 0; i < skills.length; i++) {
			skill+="<li>"+skills[i]+"</li>\n";
			}
			document.querySelector("#skill").innerHTML = skill ;
			document.querySelector("#skills").value="";
			}
		var projects = []
		function AddProj() {
			var proj="";
			projects.push(document.querySelector("#proj").value);
			for (var i = 0; i < projects.length; i++) {
			proj+="<li>"+projects[i]+"</li>\n";
			}
			document.querySelector("#projects").innerHTML = proj ;
			document.querySelector("#proj").value="";
			}
		function AddAchievement(){
			document.querySelector("#achieve").innerHTML = "<i class='fas fa-check'></i><b>&nbsp;Added</b>";
			document.querySelector("#certi").value = "";
			document.querySelector("#rank").value = "";
			document.querySelector("#Institute").value = "";
			document.querySelector("#describe").value = "";
		}
		function AddExtra(){
			document.querySelector("#extra").innerHTML = "<i class='fas fa-check'></i><b>&nbsp;Added</b>";
			document.querySelector("#course").value = "";
			document.querySelector("#inst").value = "";
			document.querySelector("#from").value = "";
			document.querySelector("#to").value = "";
		}
		function remove(){
			document.querySelector("#achieve").innerHTML = "";
			document.querySelector("#extra").innerHTML = "";
		}

	</script>
</head>

<body>
  <div class="container">
		<div class= "box-main">

  <form id="regForm"  method="POST">
  	{% csrf_token %}
  	<h1 style="text-align: center;">EDIT PROFILE</h1>

  	<div class="tab">
   		<h3 class="details">PERSONAL DETAILS</h3>
			    <label>Name:</label>
			    <input placeholder="Enter your First name"  name="fname">
			    <input placeholder=" Enter your Last name"  name="lname">
			    <br>
			    <label>SAP ID:</label>
			    <input placeholder="Enter your SAP ID" name="sap">
			    <br>
			    <label>Contact Info:</label>
			    <input placeholder="Enter your E-mail"  name="email">
			    <input placeholder="Enter your Phone"  name="phone">
			    <br>
			    <label>Birthday:</label>
			    <input type="date"  name="dob">
			    <br>
    </div>

  	<div class="tab">
    	<h3 class="details">PROFESSIONAL SUMMARY</h3>
    	<i>Write abote your position and work</i><br><br>
	    <input id="describe" placeholder="Give your Description" name="profsum">
  	</div>

  	<div class="tab">
	    <h3 class="details">QUALIFICATIONS</h3>
	    <i>Enter degrees you have persued!</i><br/><br/>
	    <label>Degree:</label>
	    <input placeholder="Enter Degree"  name="degree" required><br>
		<label>Year of passing:</label>
	    <input placeholder="Enter Year of passing"  name="year" required><br/><br/>
	    <label>Institute name:</label>
	    <input placeholder="Enter Schoolname"  name="school" required><br><br>
   	    <button type="button" id="adddegree" class="btn btn-primary">ADD</button>
  	</div>

 	<div class="tab">
	    <h3 class="details">SPECIALIZATION</h3>
	    <i>"Enter fields you have specialized in!"</i><br/><br/>
	    <label>Specialized Fields:</label>
	    <input placeholder="Enter Field name you have specialized in"  name="field" required><br><br>
	   	<button type="button" id="addcerti" class="btn btn-primary">ADD</button>
  	</div>

  	<div class="tab">
	    <h3 class="details">SKILLS, RESEARCHS & PROJECTS</h3>
		      <table>
		      <tr>
		      <td>
		      <label>SKILLS:</label>
		      <input placeholder="Skills" id="skills" name="skills" >
		  	  </td>
		  	  <td>
		  	  <label>PROJECTS:</label>
		      <input placeholder="Project link" id="proj" name="proj">
		  	  </td>
		  	  </tr>
		  	  <tr>
		  	  	<td><button type="button" id="addskill" class="btn btn-primary" style="float: right" onclick="AddSkill()">ADD</button><br/><br/></td>
		      	<td><button type="button" id="addproj" class="btn btn-primary" style="float: right" onclick="AddProj()">ADD</button><br/><br/></td>
		      </tr>
		      <tr>
		      	<td>
		      		<ul id="skill">
		      		</ul>
		      	</td>
		      	<td>
		      		<ul id="projects">
		      		</ul>
		      	</td>
		      </tr>
		      </table>
    </div>

    	<div style="overflow:auto;">
			      <input type="submit"  class="btn btn-success" style="margin-left: 920px; margin-top: 50px;"  id="savebtn"></input>

     </div></form>
 </div></div>
</body>

</html>

Teachers/templates/Teachers/mainpage.html
{% extends 'Teachers/base_teach.html' %}
{%  load static from staticfiles %}

{% block content %}
	<div class="container">
		<a style="text-decoration: none;" href="{% url 'Teachers:editprofile' %}"><button type="button" class="btn btn-danger" style="float: right;" ><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="padding-right:5px;"></span> Edit Profile</button></a>
		<br>
		<br>
		<br>
		<div class= "box-main">
			<div class="box-der green">
				<span style="padding-left: 10px; color:#9EA6BB;"><em>About me</em></span>
			</div>
			<h4 class="details">Professional Summary</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					
					<br>
					{{edittt.prof}}
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Qualification</h4>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Specialization</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Skills</h4>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der green">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<h4 class="details">Projects and research</h4>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
			<div class="box-der red">
				<strong class="head"><u>About me</u></strong>
				<div class="desc">
					Detail1
					<br>
					Detail2
					<span style="float:right; margin-right: 10px;"><a href="teacher_prof.html" style="color:black;"><i class="fas fa-trash-alt"></i></a></span>
				</div>
			</div>
		</div>
		<div style="clear: both;"></div>
	</div>
{% endblock %}